repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: examples
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black
            args:
                - "--line-length=120"

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
          - id: mypy
            additional_dependencies:
                - pydantic
                - types-PyYaml==6.0
                - types-requests

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: "v0.4.2"
      hooks:
          - id: ruff

    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: "v3.2.0"
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
            args: []

    - repo: https://github.com/python-poetry/poetry
      rev: "1.8.0"
      hooks:
          - id: poetry-check
